export const incomeContent = [
    {name: 'KİŞİ / ŞİRKET ADI', accessor: 'getTransactionTitle', type: 'String'},
    {name: 'TAHSİL EDEN',	accessor: 'getReceivedBy', type: 'String'},
    {name: 'İŞLEM TARİHİ', accessor: 'getTransactionDate',	type: 'Date'},
    {name: 'GELİR DURUMU', accessor: 'getIsCancelled', type: 'Boolean'},
    {name: 'ODA', accessor: 'getBranchId', type: 'Long'},
    {name: 'TOPLAM TUTAR', accessor: 'getAmount', type: 'BigDecimal'},
    {name: '(1. KALEM) AÇIKLAMA', accessor: 'getItemDetail', type: 'String'},
    {name: '(1. KALEM) GELİR KANALI', accessor: 'getTransactionChannelId', type: 'Long'},
    {name: '(1. KALEM) MİKTAR', accessor: 'getAmount', type: 'BigDecimal'},
    {name: '(1. KALEM) GELİR TİPİ', accessor: 'getTransactionTypeId', type: 'Long'},
    {name: '(2. KALEM) AÇIKLAMA', accessor: 'getItemDetail', type: 'String'},
    {name: '(2. KALEM) GELİR KANALI', accessor: 'getTransactionChannelId', type: 'Long'},
    {name: '(2. KALEM) MİKTAR', accessor: 'getAmount', type: 'BigDecimal'},
    {name: '(2. KALEM) GELİR TİPİ', accessor: 'getTransactionTypeId', type: 'Long'},
    {name: '(3. KALEM) AÇIKLAMA', accessor: 'getItemDetail', type: 'String'},
    {name: '(3. KALEM) GELİR KANALI', accessor: 'getTransactionChannelId', type: 'Long'},
    {name: '(3. KALEM) MİKTAR', accessor: 'getAmount', type: 'BigDecimal'},
    {name: '(3. KALEM) GELİR TİPİ', accessor: 'getTransactionTypeId', type: 'Long'},
];

export const expenseContent = [
    {name: 'KİŞİ / ŞİRKET ADI', accessor: 'getTransactionTitle', type: 'String'},
    {name: 'TAHSİL EDEN',	accessor: 'getReceivedBy', type: 'String'},
    {name: 'İŞLEM TARİHİ', accessor: 'getTransactionDate',	type: 'Date'},
    {name: 'GİDER DURUMU', accessor: 'getIsCancelled', type: 'Boolean'},
    {name: 'ODA', accessor: 'getBranchId', type: 'Long'},
    {name: 'TOPLAM TUTAR', accessor: 'getAmount', type: 'BigDecimal'},
    {name: '(1. KALEM) AÇIKLAMA', accessor: 'getItemDetail', type: 'String'},
    {name: '(1. KALEM) GİDER KANALI', accessor: 'getTransactionChannelId', type: 'Long'},
    {name: '(1. KALEM) MİKTAR', accessor: 'getAmount', type: 'BigDecimal'},
    {name: '(1. KALEM) GİDER TİPİ', accessor: 'getTransactionTypeId', type: 'Long'},
    {name: '(2. KALEM) AÇIKLAMA', accessor: 'getItemDetail', type: 'String'},
    {name: '(2. KALEM) GİDER KANALI', accessor: 'getTransactionChannelId', type: 'Long'},
    {name: '(2. KALEM) MİKTAR', accessor: 'getAmount', type: 'BigDecimal'},
    {name: '(2. KALEM) GİDER TİPİ', accessor: 'getTransactionTypeId', type: 'Long'},
    {name: '(3. KALEM) AÇIKLAMA', accessor: 'getItemDetail', type: 'String'},
    {name: '(3. KALEM) GİDER KANALI', accessor: 'getTransactionChannelId', type: 'Long'},
    {name: '(3. KALEM) MİKTAR', accessor: 'getAmount', type: 'BigDecimal'},
    {name: '(3. KALEM) GİDER TİPİ', accessor: 'getTransactionTypeId', type: 'Long'},
];

export const memberContent = [
    {name: 'İL' },
    {name: 'ODA SİCİL NO' },
    {name: 'AD' },
    {name: 'SOYAD' },
    {name: 'ESKİ SOYAD' },
    {name: 'TC KİMLİK NO' },
    {name: 'MAİL'},
    {name: 'CİNSİYET' },
    {name: 'BABA ADI' },
    {name: 'ANA ADI' },
    {name: 'DOĞUM YERİ' },
    {name: 'DOĞUM TARİHİ' },
    {name: 'KİMLİK TİPİ' },
    {name: 'KİMLİK SERİ NO' },
    {name: 'KİMLİK KAYIT NO' },
    {name: 'KİMLİK SON GEÇERLİLİK TARİHİ'  },
    {name: 'KAN GRUBU' },
    {name: 'MEDENİ HALİ' },
    {name: 'İŞ TEL' },
    {name: 'GSM TEL' },
    {name: 'EV TEL' },
    {name: 'İKAMET ADRESİ' },
    {name: 'İKAMET EDİLEN ŞEHİR' },
    {name: 'İKAMET EDİLEN İLÇE' },
    {name: 'İKAMET EDİLEN SEMT'},
    {name: 'İŞ ADRESİ' },
    {name: 'İŞ YERİ ŞEHİR' },
    {name: 'İŞ YERİ İLÇE' },
    {name: 'İŞ YERİ SEMT'},
    {name: 'ODA KAYIT TARİHİ' },
    {name: 'OPTISYENLIK MÜESSESESİ RUHSATNAMESİ BELGE NO'  },
    {name: 'OPTISYENLIK MÜESSESESİ RUHSATNAMESİ BELGE TARİHİ'  },
    {name: 'MEZUNİYET BELGE TİPİ' },
    {name: 'ÜNİVERSİTE/RUHSAT VEREN KURUM' },
    {name: 'DİPLOMA NO./GÖZL.RUHSAT. CİLT-YAPRAK NO' },
    {name: 'MEZUNİYET/GÖZL.RUHSAT. TARİHİ' },
    {name: 'VERGİ DAİRESİ ADI' },
    {name: 'VERGİ NO'  },
    {name: 'ÜYE ÇALIŞIYOR' },
    {name: 'KENDİ İŞ YERİ' },
    {name: 'MESUL MÜDÜR' },
    {name: 'KAMU PERSONELİ' },
    {name: 'ECZACI'},
    {name: 'MÜESSESE/FİRMA ADI'},
    {name: 'MÜESSESE SAHİBİ'},
    {name: 'KULLANICI ADI'},
];

export const feeDefinitonContent = [
    {name: 'ÜYE AD' },
    {name: 'ÜYE SOYAD' },
    {name: 'ODA ADI' },
    {name: 'ODA SİCİL NO' },
    {name: 'İL' },
    {name: 'TAHAKKUK YILI' },
    {name: 'TAHAKKUK TİPİ' },
    {name: 'TAHAKKUK TUTARI' },
    {name: 'TAHAKKUK OLUŞTURMA DURUMU' },
];

export const accrualContent = [
    {name: 'ÜYE AD' },
    {name: 'ÜYE SOYAD' },
    {name: 'ODA ADI' },
    {name: 'ODA SİCİL NO' },
    {name: 'İL' },
    {name: 'TAHAKKUK YILI' },
    {name: 'TAHAKKUK TİPİ' },
    {name: 'TAHAKKUK TUTARI' },
    {name: 'TAHSİL EDİLME DURUMU' },
    {name: 'TAHSİL EDEN'},
    {name: 'İŞLEM TARİHİ'},
];
export const balanceContent = [
    {name: 'GELİR TİPİ'},
    {name: 'TOPLAM TUTAR'},
    {name: 'GİDER TİPİ'},
    {name: 'TOPLAM TUTAR'},
];